import React from "react";
import { Container, Typography, Box } from "@mui/material";
import styles from "./TermsAndConditions.module.scss";

const TermsAndConditions = () => {
  return (
    <Container maxWidth="lg" sx={{ mt: 10, mb: 4 }}>
      <Typography
        variant="h5"
        align="center"
        gutterBottom
        sx={{
          fontSize: "2.8rem",
          fontWeight: "bold",
          letterSpacing: "2px",
          textTransform: "uppercase",
        }}
      >
        <span style={{ color: "#062d72" }}>BIDDING</span>
        <span style={{ color: "#05baee" }}> KARO</span>
      </Typography>

      <Typography
        variant="h6"
        align="center"
        gutterBottom
        className={styles["heading-with-lines"]}
      >
        Terms and Conditions
      </Typography>
      <Box sx={{ p: 3 }}>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          <strong>1. License:</strong> This document is an electronic record as
          defined by the Information Technology Act, 2000 (“IT Act, 2000”) and
          related statutes. It is generated by a computer system and does not
          require any physical or digital signatures.
        </Typography>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          • In compliance with Rule 3 (1) of the Information Technology
          (Intermediaries Guidelines) Rules, 2011, which requires the
          publication of rules and regulations, privacy policy, and terms of use
          for accessing or using the website at www.biddingkaro.in (the
          “Platform”), we hereby publish the following terms of use.
        </Typography>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          • The Platform, including the related mobile site, mobile application,
          and web portal, is owned and operated by Bidding Genie Private Limited
          (“Bidding Karo”), a company incorporated under the Companies Act,
          1956, with its registered office at First Floor, Shri Ram Market,
          Sector 86, Tigaon Road, Faridabad, Haryana 121002.
        </Typography>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          • Throughout these Terms of Use, “you” and “your” refer to any natural
          or legal person who has registered to become a user of the Platform
          using computer systems. The term “user” collectively refers to
          sellers, buyers, and visitors on the Platform, while “we,” “us,” and
          “our” refer to Bidding Karo.
        </Typography>
      </Box>
      <Box sx={{ p: 3 }}>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          <strong>2. Enrolment Eligibility:</strong> To use the Platform, you
          must complete the registration process for one or more of the Services
          offered. Use of the Services is restricted to parties that can
          lawfully enter into contracts under applicable law. As part of the
          registration process, you must provide us with your legal name,
          address, phone number, email address, applicable tax registration
          details, and any other information we may require. Any personal data
          you provide to us will be handled in accordance with the Bidding Genie
          Privacy Policy.
        </Typography>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          • Bidding Karo reserves the right to terminate or remove your
          registration and/or deny you access to the Platform if we become aware
          that you are not seriously participating in bid whether you are Buyer
          or Supplier or if you violate any of the Terms of Use . If you
          register on behalf of a business entity, you represent and warrant
          that you are authorized by the business entity to accept the Terms of
          Use on its behalf and that you have the authority to bind the business
          entity to the Terms of Use. Using platform means you have accepted the
          terms and conditions and other policies on this platform and you are
          aware that the bidding Karo does not own responsibility for any losses
          due to decisions taken on the basis of the information provide here as
          all the information on the platform are provided by the users only and
          we doesn’t own any responsibility.
        </Typography>
      </Box>
      <Box sx={{ p: 3 }}>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          <strong>3. Services Offered:</strong> Bidding Karo provides a
          comprehensive suite of services designed to streamline and optimize
          the sourcing process using system programming or Artificial
          Intelligence (AI) wherever required. Our AI-based Sourcing Application
          (AISA) offers the following services:
        </Typography>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          • Vendor Search and Listing: - Vendor Identification: Upon entering
          your sourcing requirements, our system will generate a list of
          potential vendors within India that might match your product
          specifications.
        </Typography>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          • Vendor Verification: The application provides vendors based on
          historical data and ratings provided by other users. Bidding Karo
          doesn’t advise to use the specific vendors and not guarantee for the
          accuracy of the ratings on the portal. Vendors or buyers selected are
          only on the self decision of the users. Bidding Karo doesn’t own any
          responsibility.
        </Typography>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          • Price Verification and Quotation: - Price Verification: The system
          automatically provides data of previous bids done by users specific
          for similar products to provide a benchmark.
        </Typography>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          • Quotation Requests: Users can request quotes from multiple vendors
          through the platform, streamlining the quotation process.
        </Typography>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          Computer System Powered Negotiation: - Automated Negotiation: Users
          can input their best sourcing price into the application, and then the
          system will negotiate with vendors to achieve the best possible price.
        </Typography>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          • Real-Time Updates: The application provides real-time updates on the
          negotiation status and final pricing offers from vendors. Terms of the
          Live biddings are on the Portal and using the live bids assumed that
          users have read the terms and Conditions of the bidding. To make
          system user friendly, Bidding Karo provides live bids status on 10
          seconds gap. Users have to make their systems updated as per the
          Bidding Karo Portal and their networks intact. Still if there is any
          problem to users during the Live bidding, Bidding Karo doesn’t own any
          responsibility related to this. All the decisions related to bidding
          allotment are solely of the Bidders. Bidder may allot the Bid to L1
          user or any other participant. Bidding Karo can’t ask the bidder to
          allot to L1 only. All the decisions are purely of the bidder. Bidding
          Karo is only the platform provided for negotiation. Participants are
          allowed to put the price against the specific products maximum upto 3
          times. On bidding the price in the live bid by the previous vendor and
          thereafter no other vendor has put the price in the live bid for that
          product till next 5 mins then the previous Participant will be
          declared as L1. Likewise when all products requirement closed for the
          specific bids then after 15 Mins that specific bids will be closed
          from the Portal.
        </Typography>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          Vendor Selection: - Optimal Vendor Recommendation: Based on price,
          quality, and other relevant factors, the application recommends the
          best vendor for your needs.
        </Typography>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          • Decision Support: Users can review detailed analytics and comparison
          reports to make informed decisions.
        </Typography>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          Letter of Intent Management: - Automated LOI: Once a vendor is
          selected, the AI system generates and sends the Letter Intent to the
          chosen vendor.
        </Typography>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          • Order Tracking: Once Letter of Intent is provided from the Bidding
          Karo, then Role of the Bidding Karo comes to an end to that specific
          bidding. Bidding Karo does not monitor whether formal Purchase order
          was issued, Delivery Schedule, actual Quality of products delivered,
          Payment against the delivery etc. Users can rate to buyers or vendors
          on their users experience so that other users must be aware of any
          experience.
        </Typography>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          Quality Assurance: - Quality Check Procedures: The Bidding Karo
          assists users to specify the quality requirements to vendors and can
          ask for the samples or visit requirement before commercial bidding.
          Bidding Karo never ensures for any quality on the delivered product.
          All quality assurance processes must be done by the buyers and vendors
          independently.
        </Typography>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          • Approval Workflows: Users can set up approval workflows where
          sourced materials are only accepted after passing quality checks by
          the Bidding Karo.
        </Typography>
        <Typography variant="body1" paragraph sx={{ textAlign: "justify" }}>
          Please note that Bidding Karo does not warrant the accuracy,
          completeness, reliability, correctness, or error-free nature of
          Product descriptions or other content on the Platform and assumes no
          liability in this regard.
        </Typography>
        <Box sx={{ textAlign: "justify", mt: 1 }}>
          <img src="./logo.png" alt="Bidding karo logo" width="180" />
        </Box>
      </Box>
    </Container>
  );
};

export default TermsAndConditions;
