export const PortalApiUrls = Object.freeze({
  GET_USER_PROFILE: "/user/customer/profile/",
  UPDATE_USER_PROFILE: "/user/customer/profile/",
  GET_ORGANIZATION_TYPE: "/company/choices/organization_type/",
  CREATE_COMPANY: "/company/customer/",
  UPDATE_COMPANY: "/company/customer/",
  GET_COMPANY_PROFILE: "/company/customer/",
  GET_CATEGORIES: "/category/",
  GET_STATES: "/global-places/states/",
  GET_CITIES: "/global-places/cities/",
  RETRIEVE_CITY: "/global-places/cities/",
  CREATE_ADDRESS: "/company/customer/address/",
  DELETE_ADDRESS: "/company/customer/address/",
  GET_CERTIFICATE_TYPE: "/company/choices/certificate_type/",
});
