export const PortalApiUrls = Object.freeze({
  GET_USER_PROFILE: "/user/customer/profile/",
  UPDATE_USER_PROFILE: "/user/customer/profile/",
  GET_ORGANIZATION_TYPE: "/company/choices/organization_type/",
  CREATE_COMPANY: "/company/customer/",
  UPDATE_COMPANY: "/company/customer/",
  GET_COMPANY_PROFILE: "/company/customer/",
  GET_CATEGORIES: "/category/",
  UPDATE_COMPANY_CATEGORIES: "/company/customer/category/",
  UPDATE_BID_CATEGORIES: "/bid/customer/category/",
  GET_STATES: "/global-places/states/",
  GET_CITIES: "/global-places/cities/",
  RETRIEVE_CITY: "/global-places/cities/",
  CREATE_ADDRESS: "/company/customer/address/",
  DELETE_ADDRESS: "/company/customer/address/",
  GET_CERTIFICATE_TYPE: "/company/choices/certificate_type/",
  CREATE_CERTIFICATE: "/company/customer/certificate/",
  DELETE_CERTIFICATE: "/company/customer/certificate/",
  CHANGE_PASSWORD: "/user/change_password/",
  GET_BID_TYPE: "/bid/choices/",
  CREATE_BID: "/bid/customer/",
  LIST_BIDS: "/bid/customer/",
  ADD_QUESTION: "/bid/customer/question/",
  DELETE_QUESTION: "/bid/customer/question/",
  UPLOAD_DOCUMENT: "/bid/customer/document/",
  RETRIEVE_BID: "/bid/customer/",
  UPDATE_BID: "/bid/customer/",
});
